//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BloodType.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BloodType.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to about.
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to blood type.
        /// </summary>
        public static string ApplicationTitle {
            get {
                return ResourceManager.GetString("ApplicationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BLOOD TYPE.
        /// </summary>
        public static string ApplicationTitleUpper {
            get {
                return ResourceManager.GetString("ApplicationTitleUpper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ChangeList.
        /// </summary>
        public static string ChangeList {
            get {
                return ResourceManager.GetString("ChangeList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FATHER&apos;S BLOOD TYPE.
        /// </summary>
        public static string DadType {
            get {
                return ResourceManager.GetString("DadType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BloodType is a simple app that you can set up your blood type and then, show it on the lockscreen. Also, it one provide a fun  action which is called &quot;find your type&quot;, where you may play with all possible combination of blood types..
        /// </summary>
        public static string Disclaimer {
            get {
                return ResourceManager.GetString("Disclaimer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feedback.
        /// </summary>
        public static string Feedback {
            get {
                return ResourceManager.GetString("Feedback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to find your type.
        /// </summary>
        public static string FindType {
            get {
                return ResourceManager.GetString("FindType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Picture.
        /// </summary>
        public static string ImagePreview {
            get {
                return ResourceManager.GetString("ImagePreview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to live tiles.
        /// </summary>
        public static string LiveTile {
            get {
                return ResourceManager.GetString("LiveTile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to lockscreen.
        /// </summary>
        public static string LockScreen {
            get {
                return ResourceManager.GetString("LockScreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to main.
        /// </summary>
        public static string Main {
            get {
                return ResourceManager.GetString("Main", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MOTHER&apos;S BLOOD TYPE.
        /// </summary>
        public static string MomType {
            get {
                return ResourceManager.GetString("MomType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MY BLOOD TYPE.
        /// </summary>
        public static string MyType {
            get {
                return ResourceManager.GetString("MyType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keep in mind that the best way to find out your blood type is through to blood test done at a health clinic!.
        /// </summary>
        public static string Notice {
            get {
                return ResourceManager.GetString("Notice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rate and Review .
        /// </summary>
        public static string Rate {
            get {
                return ResourceManager.GetString("Rate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aplication version: 1.3.
        /// </summary>
        public static string Release {
            get {
                return ResourceManager.GetString("Release", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LeftToRight.
        /// </summary>
        public static string ResourceFlowDirection {
            get {
                return ResourceManager.GetString("ResourceFlowDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to en-US.
        /// </summary>
        public static string ResourceLanguage {
            get {
                return ResourceManager.GetString("ResourceLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sample Runtime Property Value.
        /// </summary>
        public static string SampleProperty {
            get {
                return ResourceManager.GetString("SampleProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select your blood type.
        /// </summary>
        public static string SelectType {
            get {
                return ResourceManager.GetString("SelectType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select the blood type of your father.
        /// </summary>
        public static string SelectTypeDad {
            get {
                return ResourceManager.GetString("SelectTypeDad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select the blood type of your mother.
        /// </summary>
        public static string SelectTypeMom {
            get {
                return ResourceManager.GetString("SelectTypeMom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to settings.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to set your type.
        /// </summary>
        public static string SetType {
            get {
                return ResourceManager.GetString("SetType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You may share your result using the app bar..
        /// </summary>
        public static string ShareSuggest {
            get {
                return ResourceManager.GetString("ShareSuggest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BloodType shared!.
        /// </summary>
        public static string ShareTitle {
            get {
                return ResourceManager.GetString("ShareTitle", resourceCulture);
            }
        }
    }
}
